DROP DATABASE IF EXISTS ESCUELA;
CREATE DATABASE ESCUELA;
USE ESCUELA;
CREATE TABLE GRADO(
cvegrado INT(1) PRIMARY KEY NOT NULL,
nomgrupo VARCHAR(25) NOT NULL
);
CREATE TABLE GRUPO(
Cvegrupo CHAR(6) PRIMARY KEY NOT NULL,
nomgrupo VARCHAR(25) NOT NULL,
Cvegrado CHAR (1)NOT NULL,
FOREIGN KEY (cvegrado) REFERENCES AREA(cvegrado)
ON UPDATE CASCADE
);
INSERT INTO GRADO VALUES('4',' AMPG');
INSERT INTO GRADO VALUES('4',' ABMPG');

